# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-02-26 09:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import squad.sprd_frontend.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0108_add_email_template_validator'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=64)),
                ('pac_node', models.CharField(default='', max_length=128)),
            ],
            bases=(models.Model, squad.sprd_frontend.models.DisplayName),
        ),
        migrations.CreateModel(
            name='TestDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=16)),
                ('content', models.TextField(default='', max_length=2048)),
                ('description', models.CharField(default='', max_length=256)),
                ('actions', models.TextField(default='', max_length=2048)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=(models.Model, squad.sprd_frontend.models.DisplayName),
        ),
        migrations.CreateModel(
            name='VtsVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=16)),
                ('vts_bar_url', models.CharField(default='', max_length=128)),
                ('description', models.CharField(default='', max_length=256)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=(models.Model, squad.sprd_frontend.models.DisplayName),
        ),
    ]
