# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-02-26 11:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import squad.sprd_frontend.models


class Migration(migrations.Migration):

    dependencies = [
        ('ci', '0023_remove_testjob_build'),
        ('core', '0108_add_email_template_validator'),
        ('sprd_frontend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VtsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=64)),
                ('options', models.CharField(default='', max_length=128)),
                ('description', models.CharField(default='', max_length=256)),
            ],
            bases=(models.Model, squad.sprd_frontend.models.DisplayName),
        ),
        migrations.RemoveField(
            model_name='testdefinition',
            name='project',
        ),
        migrations.AddField(
            model_name='devicetype',
            name='backend',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ci.Backend'),
        ),
        migrations.AddField(
            model_name='devicetype',
            name='env',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Environment'),
        ),
        migrations.AddField(
            model_name='devicetype',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Project'),
        ),
        migrations.AddField(
            model_name='vtsmodel',
            name='test_definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sprd_frontend.TestDefinition'),
        ),
    ]
