# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-02-27 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprd_frontend', '0002_auto_20190226_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetype',
            name='slug',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='testdefinition',
            name='actions',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='testdefinition',
            name='content',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
