# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-02-27 05:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprd_frontend', '0003_auto_20190227_0505'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetype',
            name='base_pac_url',
            field=models.CharField(default='', max_length=128),
        ),
    ]
